version: '3.3'
services:
  app:
    container_name: docker-postgres-node
    restart: always
    build: . 
    ports:
      - "80:3001"
    links: [db]
  db:
    container_name: postgres_docker
    image: postgis/postgis:15-3.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: anapitalai@gmail.com
      PGADMIN_DEFAULT_PASSWORD: noGoZone
    ports:
      - "5050:80"